'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		Friend ReadOnly Property AttachFile() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AttachFile", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BookNote() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BookNote", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property BookNoteWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BookNoteWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Charts() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Charts", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CheckMark() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CheckMark", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ColorScheme() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ColorScheme", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property contact() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("contact", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Delete() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Delete1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Delete1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property DeleteWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("DeleteWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Details() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Details", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Help() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Invoice() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Invoice", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice1() As String
			Get
				Return ResourceManager.GetString("Invoice1", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice2() As String
			Get
				Return ResourceManager.GetString("Invoice2", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice3() As String
			Get
				Return ResourceManager.GetString("Invoice3", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice4() As String
			Get
				Return ResourceManager.GetString("Invoice4", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice5() As String
			Get
				Return ResourceManager.GetString("Invoice5", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice6() As String
			Get
				Return ResourceManager.GetString("Invoice6", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
		'''{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \froman\fcharset0\fprq2{ [rest of string was truncated]&quot;;.
		''' </summary>
		Friend ReadOnly Property Invoice7() As String
			Get
				Return ResourceManager.GetString("Invoice7", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property MarkAsPaid() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MarkAsPaid", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property MarkAsPaidWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("MarkAsPaidWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NewInvoice() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NewInvoice", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NewInvoice1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NewInvoice1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NewInvoiceWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NewInvoiceWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property NewNote() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NewNote", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PaperClip() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PaperClip", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PaperClipWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PaperClipWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Person() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Person", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Print() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Print1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Print1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property PrintWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("PrintWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Table() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Table", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Table1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Table1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TableReportt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TableReportt", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TableSelectRow() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TableSelectRow", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TableWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TableWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property TableWhite1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TableWhite1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Unpaid() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Unpaid", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property User() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property User1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("User1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property User3() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("User3", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property UserWhite() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("UserWhite", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property UserWhite1() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("UserWhite1", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Web() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property
	End Module
End Namespace
