'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		Friend ReadOnly Property BreakingNews() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("BreakingNews", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property CommandPrompt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CommandPrompt", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Computer() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Computer", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ControlPanel() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ControlPanel", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Debug() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Debug", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property GreenBack() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("GreenBack", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property IELogo() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("IELogo", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property News() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("News", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property Remote() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Remote", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property ShoppingBag() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("ShoppingBag", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		Friend ReadOnly Property WinDesktop() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("WinDesktop", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property
	End Module
End Namespace
